version: "3.7"
services:
  mqbroker:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  accesspoint:
    image: rektranetwork/trekt.accesspoint:test-latest
    command: -name p80 -unsecured -host accesspoint:8080 -mq_broker mqbroker
    depends_on:
      - mqbroker
      - auth
    ports:
      - 80:8080
  auth:
    image: rektranetwork/trekt.auth:test-latest
    command: -name 1 -mq_broker mqbroker
    depends_on:
      - mqbroker